name: ForumSync
main: me.sisko.forums.Core
version: 1.1
depend: [Vault]
commands:
  register:
    description: Creates a forum account
    usage: /register <email> <password>
  forum:
    description: Forum admin command
    usage: /forum <reload|checkaccount>
    permission: forum.admin
  changepassword:
    description: Changes your forum password
    usage: /changepassword <newpassword>
  forumsync:
    description: Syncs your in-game rank with forum rank
    usage: /forumsync